-- CREATE CUSTOMER_USERS TABLE
-- Copy and paste this SQL into Supabase SQL Editor
-- https://supabase.com/dashboard/project/qjtkvvmvbbisrdbsxmuk/sql

-- 1. Create the table
CREATE TABLE IF NOT EXISTS public.customer_users (
id bigint generated by default as identity primary key,
customer_id text not null references public.customers(id) on delete cascade,
email text not null unique,
full_name text,
is_primary boolean default false,
is_active boolean default true,
created_at timestamp with time zone default timezone('utc'::text, now()) not null,
updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Add indexes
CREATE INDEX IF NOT EXISTS customer_users_customer_id_idx ON public.customer_users(customer_id);
CREATE INDEX IF NOT EXISTS customer_users_email_idx ON public.customer_users(email);
CREATE INDEX IF NOT EXISTS customer_users_is_active_idx ON public.customer_users(is_active);

-- 3. Add constraint: Only one primary user per customer
CREATE UNIQUE INDEX IF NOT EXISTS customer_users_primary_unique_idx 
ON public.customer_users(customer_id) 
WHERE is_primary = true and is_active = true;

-- 4. Enable RLS
ALTER TABLE public.customer_users ENABLE ROW LEVEL SECURITY;

-- 5. Add RLS policies
DROP POLICY IF EXISTS "Users can view own customer users" ON public.customer_users;
CREATE POLICY "Users can view own customer users" ON public.customer_users
FOR SELECT USING (
  customer_id IN (
    SELECT customer_id FROM public.customer_users 
    WHERE email = auth.jwt() ->> 'email'
  )
);

DROP POLICY IF EXISTS "Service role can manage all customer users" ON public.customer_users;
CREATE POLICY "Service role can manage all customer users" ON public.customer_users
FOR ALL USING (auth.role() = 'service_role');

-- 6. Add comments
COMMENT ON TABLE public.customer_users IS 'Maps email addresses to customers - allows multiple users per customer/contract';

-- 7. Test with sample data
INSERT INTO public.customer_users (customer_id, email, full_name, is_primary, is_active) VALUES
('21', 'hotel-medena-seget-d@test.hr', 'HOTEL MEDENA - SEGET DONJI - Glavni kontakt', true, true),
('21', 'nabava-hotel-medena-seget-d@test.hr', 'HOTEL MEDENA - SEGET DONJI - Nabava', false, true),
('29', 'djeji-vrti-ibenska-m@test.hr', 'DJEČJI VRTIĆ ŠIBENIČKA MALA ŠKOLA d.o.o. - Glavni kontakt', true, true)
ON CONFLICT (email) DO NOTHING;

-- 8. Verify setup
SELECT 
'customer_users table created' as status,
COUNT(*) as total_users,
COUNT(*) FILTER (WHERE is_primary = true) as primary_contacts
FROM public.customer_users;